# Generated by Django 5.2.8 on 2026-05-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiracleEucharistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('est_publie', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(blank=True, max_length=120)),
                ('pays', models.CharField(blank=True, max_length=120)),
                ('date_evenement', models.DateField(blank=True, null=True)),
                ('periode_affichage', models.CharField(blank=True, help_text='Ex. An 1254, 1996, Pentecote 2000.', max_length=120)),
                ('personne_liee', models.CharField(blank=True, help_text='Ex. Carlo Acutis, Sainte Claire, Claudio Gatti.', max_length=255)),
                ('resume', models.TextField(blank=True, help_text='Courte introduction qui presente le miracle.')),
                ('recit', models.TextField(help_text='Recit principal du miracle.')),
                ('analyse_scientifique', models.TextField(blank=True, help_text="Resultats d'enquetes, expertises ou constatations.")),
                ('devotion_associee', models.TextField(blank=True, help_text='Priere, litanie ou meditation attachee au miracle.')),
                ('source', models.TextField(blank=True, help_text='Reference bibliographique, citation ou temoignage.')),
                ('source_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'miracle eucharistique',
                'verbose_name_plural': 'miracles eucharistiques',
                'ordering': ('ordre_affichage', 'titre'),
            },
        ),
        migrations.CreateModel(
            name='Priere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('est_publie', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.CharField(choices=[('quotidienne', 'Quotidienne'), ('intercession', 'Intercession'), ('devotion', 'Devotion'), ('penitence', 'Penitence'), ('protection', 'Protection'), ('repas', 'Repas'), ('eglise', 'Eglise'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('intention', models.CharField(blank=True, help_text='Ex. paix, malades, defunts, familles, vocations.', max_length=255)),
                ('introduction', models.TextField(blank=True, help_text="Petit texte d'introduction ou contexte d'utilisation.")),
                ('texte', models.TextField(help_text='Texte complet de la priere.')),
                ('contient_variables', models.BooleanField(default=False, help_text='Cochez si la priere contient des champs comme [Nom du malade].')),
                ('notes_utilisation', models.TextField(blank=True, help_text='Indications pastorales ou liturgiques optionnelles.')),
                ('miracle_associe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prieres_associees', to='LumenChristiilluminanos_app.miracleeucharistique')),
            ],
            options={
                'verbose_name': 'priere',
                'verbose_name_plural': 'prieres',
                'ordering': ('ordre_affichage', 'titre'),
            },
        ),
    ]
